<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-06-27T17:16:36Z" name="Default suite" finished-at="2018-06-27T17:17:19Z" duration-ms="43832">
    <groups>
    </groups>
    <test started-at="2018-06-27T17:16:36Z" name="Default test" finished-at="2018-06-27T17:17:19Z" duration-ms="43832">
      <class name="com.crm.qa.testcases.HomepageTest">
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.crm.qa.testcases.HomepageTest@175b9425]" started-at="2018-06-27T17:16:36Z" name="setUP" finished-at="2018-06-27T17:17:19Z" duration-ms="43099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="verifyhomepageTitleTest()[pri:0, instance:com.crm.qa.testcases.HomepageTest@175b9425]" started-at="2018-06-27T17:17:19Z" name="verifyhomepageTitleTest" finished-at="2018-06-27T17:17:19Z" duration-ms="34" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is not correct expected [CRMPRO123] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is not correct expected [CRMPRO123] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.crm.qa.testcases.HomepageTest.verifyhomepageTitleTest(HomepageTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyhomepageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.testcases.HomepageTest@175b9425]" started-at="2018-06-27T17:17:19Z" name="tearDown" finished-at="2018-06-27T17:17:19Z" duration-ms="655" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.testcases.HomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
